name: Task / Feature
description: 새로운 작업(Task) 또는 기능(Feature)을 등록합니다.
title: "[Task]: "
labels: ["feature", "task"]
assignees: []
type: task

body:
  - type: markdown
    attributes:
      value: |
        새로운 작업을 등록해주셔서 감사합니다.
        아래 내용을 채워서 작업 의도를 명확히 해주세요.

  - type: input
    id: summary
    attributes:
      label: 작업 요약
      description: 이 작업의 핵심 목적을 한 줄로 적어주세요.
      placeholder: ex. 로그인 API 구현
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 상세 설명
      description: 작업의 목적, 배경, 기대 흐름, 주요 구현 내용을 구체적으로 적어주세요.
      placeholder: 여기서 자세한 내용을 설명하세요.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 기준 (Acceptance Criteria)
      description: 이 작업이 완료되었다고 판단할 수 있는 조건을 체크리스트 형태로 작성해주세요.
      placeholder: |
        - [ ] 조건 1
        - [ ] 조건 2
        - [ ] 조건 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 작업의 중요도 수준을 선택해주세요.
      options:
        - 낮음
        - 보통
        - 높음
      default: 1
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 작업 분류
      description: 이 작업이 어느 영역에 해당하는지 선택해주세요.
      options:
        - Frontend
        - Backend
        - Infra
        - Database
        - Documentation
      default: 0

  - type: textarea
    id: dependencies
    attributes:
      label: 관련 이슈 / 의존성
      description: 이 작업과 관련된 다른 이슈나 PR이 있다면 적어주세요.
      placeholder: |
        관련: #12, #21  
        Blocked by: #8

  - type: textarea
    id: additional-info
    attributes:
      label: 추가 정보
      description: 필요한 추가 정보나 참고 사항이 있다면 자유롭게 적어주세요.
      placeholder: 여기에 추가 설명을 적어주세요.

  - type: checkboxes
    id: terms
    attributes:
      label: 확인 사항
      description: 아래 항목을 확인해주세요.
      options:
        - label: 이 작업은 현재 프로젝트의 목적과 방향에 부합합니다.
          required: true
