#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+')

if [ -n "$ISSUE_NUMBER" ]; then
  sed -i.bak -e "1s/^/(#$ISSUE_NUMBER) /" "$COMMIT_MSG_FILE"
fi